### ISSUE TITLE
OSM object overwritten with old version

### ISSUE THREAD

**Issue by schuetzm** [sozialhelden/wheelmap-frontend#280]
Hi, I'm not sure whether this is the right place to report this...

Please have a look at this [changeset on OSM](https://www.openstreetmap.org/changeset/94553642) which says "Modified via wheelmap.org". Here, a user changed some tags on an object (a chapel, [link on Wheelmap](https://wheelmap.org/nodes/-61796218)). If you look at the object's [history](https://www.openstreetmap.org/way/61796218/history), you'll see that the change replaced some tags (e.g. `denomination`, `building`) with the values they had when the same user last edited the object two years ago, and it also removed several `addr:*` tags that weren't there at that time. Curiously, some other tags that were added later have not been touched.

Do you have an explanation for this? Note that I didn't contact the user yet because I didn't want to bother him with this problem, as I suspect it's a bug in Wheelmap. Or is this an already fixed bug, and he's simply using an old version of the app? Then I'll send him a message and ask him to update.

**Comment by opyh** [comment]
Thanks for this detailed report and your offer to help, much appreciated! 🙂

This changeset must have been generated by a very old version of a Wheelmap app. As there is no means to deactivate this app remotely, it would be helpful if you write the message as you proposed. Thanks again!

Feel free to reopen if there is more to add here.
