### ISSUE TITLE
changeset does not close after 22h

### ISSUE THREAD

**Issue by mfrasca** [sozialhelden/wheelmap-frontend#329]
**Describe the bug**
changeset https://www.openstreetmap.org/changeset/114241653 was opened at 2021-11-26T00:16:43Z, and at the time of writing is still open.

**Expected behavior**
an idea could be to close the changeset as soon as the next item goes at more than 200m away from the previous element.

could it be something being changed while processing older bug #327?

**Comment by mfrasca** [comment]
the same is happening with https://www.openstreetmap.org/changeset/114281829, opened shortly after 00:00Z (that's about 12 hours ago at the moment of writing), still open, cumulating contributions from all over the world.

**Comment by opyh** [comment]
Thanks for this issue! We are in the middle of rewriting the process how Wheelmap syncs OSM data. One goal is to create more manageable changesets. I‘m sorry I can’t tell you an exact date when all this will be finished. Will keep you posted :)

**Comment by mfrasca** [comment]
hi. if you mark all your commits with #329, before you push them to this public repository, we can follow what you're doing and who knows even help you in the process.  I had a look at some of your links, but did not understand how it fits with the interaction with OSM.

**Comment by mfrasca** [comment]
am I guessing correctly, you have reduced the span from 24h to 1h?  this does reduce the symptoms, I hope your team won't consider the issue solved.  :wink:

**Comment by opyh** [comment]
No worries :)

In an upcoming version, changing a place's wheelchair accessibility on Wheelmap will synchronously create one changeset. No asynchronous queue. While this will fail more often, people will [get early feedback if something does not work](https://www.martinfowler.com/ieeeSoftware/failFast.pdf).

Background: We have experienced that because edits do not get propagated to OSM directly, people knowing how OSM works are afraid to lose their edits. Data should simply not be visibly out of sync between Wheelmap and OSM.

We can tag changesets with meta-information like a random (anonymous) browser session ID, and mapathon information, if existent. This way, edits that have something in common get more transparent.

**Comment by Lee-Carre** [comment]
> While this will fail more often, people will [get early feedback if something does not work](//www.martinfowler.com/ieeeSoftware/failFast.pdf).

Eric Raymond's [The Art of Unix Programming § Rule of Repair: Repair what you can — but when you must fail, **fail noisily and as soon as possible**](http://www.catb.org/esr/writings/taoup/html/ch01s06.html#id2878538)

**Comment by opyh** [comment]
The PR mentioned above will create atomic changesets, as described above. It's not in there yet, but will be soon. There will be an intermediate beta deployment to test this feature.

**Comment by nero-still** [comment]
Tach Herr Zappe :-) 

Könntest Du mich aus den Wheelmap-Banachrichtigungen rausnehmen?

Viele Grüße & Vielen Dank,
Rainer

________________________________________________

Interaction / Visual Designer

Mobil: +49 157 525 00 922

Framefield GmbH
Paul-Robeson-Straße 46  Telefon: +49-30-60 052 742
D-10439 Berlin Internet: www.framefield.com

Sitz der Gesellschaft: Berlin; USt-IdNr.: DE283994303
Handelsregister: Amtsgericht Charlottenburg - HRB 142573 B

**Comment by opyh** [comment]
We're currently working on this in https://github.com/sozialhelden/wheelmap-frontend/pull/372. You will be able to create changesets using your OSM account.

**Comment by opyh** [comment]
Closing changesets instantly seems to work in a test. https://www.openstreetmap.org/changeset/133760058

It will still take a while to polish the new app for a public release.

**Comment by mfrasca** [comment]
this [came up again](https://t.me/OpenStreetMapOrg/102497) in the OSM generic Telegram group.
![image](https://github.com/sozialhelden/wheelmap-frontend/assets/122869/d9a93bca-970a-4624-b190-17271ecbd587)

**Comment by opyh** [comment]
The beta deployment that fixes this issue is online ([blog post](https://news.wheelmap.org/en/improved-wheelmap-test-it-now-and-rate-even-more-places/), [beta.wheelmap.org](https://beta.wheelmap.org)). Waiting for community feedback, then this will go into production.

**Comment by opyh** [comment]
This seems to work reliably. Please reopen if you see something that I might have missed.
