### ISSUE TITLE
Update: Leaflet version 1.7.1

### ISSUE THREAD

**Issue by tmiaa** [sozialhelden/wheelmap-frontend#336]
I see the leaflet version is "leaflet": "^1.0.3", can this be updated?

**Comment by tmiaa** [comment]
🙏🏼

**Comment by opyh** [comment]
I wish, but the map tile layer implementation relies on an internal Leaflet API that has changed in the meantime. This means a Leaflet update would break other things.

It's likely that we will move to something else than Leaflet in the near future.

Out of curiosity, do you have a specific reason for this request? UX? Something else?

**Comment by tmiaa** [comment]
I saw some accessibility problems and was thinking it would be better with some updates since 1.7.1. But you can close this if you want :)

**Comment by opyh** [comment]
True, the map component's accessibility could be better. When we switch to new mapping component, we'll have a thorough look into this topic. Optimally there would be additional list-based views of the map content, but I can't say if/when we'll have the resources to implement this.
