### ISSUE TITLE
Display ground surface conditions around places

### ISSUE THREAD

**Issue by HerrLederer** [sozialhelden/wheelmap-frontend#350]
Hi community,
It is not only doorsteps that make life hard. While contributing to this great project I noticed that also sandy, gravel or pebble grounds make life hard. However, this is easily compensated by shop owners who gladly provide their services outside their shops by actively approaching wheelchair users.

**Describe the solution you'd like**
In my particular situation there is a food stand next to my company. Even though there are no steps anywhere, the food stand has a gravel ground around it which makes it impossible to reach the stand. However the owner is a warm-hearted guy who will approach wheelchair users and provide them with food. Maybe we should add another option for the ground surface like "easy", "somewhat stable", "hard to tackle", "impossible to get through". I guess OpenStreetMap needs some extension to it. Also I propose that hints towards extra help should be added. I know, that's just the start of some larger discussion regarding data models, so I'll be patient. Just adding my 2cc.

**Describe alternatives you've considered**
I considered adding incorrect data marking that food stand to be "lots of stairs", but that ain't true since anyone going there will receive food. I don't like having incorrect data.

**Additional context**
I'd gladly help implementing this change.

**Comment by opyh** [comment]
Good point :) We're working on this issue already. You can already tag surface / ground conditions on OpenStreetMap now:

- [`surface` Tag on OpenStreetMap](https://wiki.openstreetmap.org/wiki/Key:surface)
- [`smoothness` Tag on OpenStreetMap](https://wiki.openstreetmap.org/wiki/Key:smoothness)

We have already begun processing this data in our OSM backend. I can't say when the data will end up in Wheelmap's UI, but it's on our roadmap.

Here is a preview of this data in our debugger, focused on a university café in Berlin:

https://sozialhelden.github.io/planet-accessibility-explorer/#/planet-accessibility-explorer/composite/amenities:617257328,buildings:40451510,pedestrian_highways:116904495?lon=13.323165369818518&lat=52.5141621303254&zoom=18.117477203547573

The ground surface conditions around the building are displayed as well.

You could help by giving feedback for this visualization. Feel free to post additional ideas if you know helpful OSM tags that are not displayed in the debugger yet :)

**Comment by opyh** [comment]
I'll close this as there is no feedback yet. Feel free to reopen.
