### ISSUE TITLE
Editing multipolygons doesn't work

### ISSUE THREAD

**Issue by map-per** [sozialhelden/wheelmap-frontend#389]
I marked this place (1) as wheelchair accessible using the "beta" version deployed at https://feature-attach-osm-api.wheelmap.tech/.
Unfortunately the edit (2) removed all members from the multipolygon.

I will fix the error in the OSM database soon.

(1) https://www.openstreetmap.org/relation/7726478
(2) https://www.openstreetmap.org/changeset/138202606

**Comment by opyh** [comment]
Thanks for this report! We found the issue behind this and we're working on a fix.

**Comment by opyh** [comment]
This was a backend issue that we have fixed and tested now. Thanks again for the report, and to @bjoernuhlig for the fix! ✨
