### ISSUE TITLE
Closed object still visible in wheelmap

### ISSUE THREAD

**Issue by jrauber** [sozialhelden/wheelmap-frontend#392]
**Describe the bug**
Closed object still visible in wheelmap

**To Reproduce**
1. Go to https://wheelmap.org/nodes/-135788963 
2. Go to https://www.openstreetmap.org/way/135788963
3. Compare

**Expected behavior**
The building is still marked as a financial institution in open wheel map, in open street map it is correctly marked as not beeing a bank anymore.

**Screenshots**

Open StreetMap
![image](https://github.com/sozialhelden/wheelmap-frontend/assets/10260156/b9035690-9930-4750-a432-22f277a980d0)

Wheelmap
![image](https://github.com/sozialhelden/wheelmap-frontend/assets/10260156/3eb62176-49df-42bb-9f31-00a154c7a523)

Wheelmap

**Desktop (please complete the following information):**
 - OS: Win 11 / Edge

**Smartphone (please complete the following information):**
 - Device: iPhone 13

**Additional context**
Happens in desktop and on mobile app

**Comment by nero-still** [comment]
Thank your for your Email. I will be out of office until August 14th.
If you have any urgent requests, please contact ***@***.***

all the best
Rainer

**Comment by opyh** [comment]
This is probably fixed in the new beta ([blog post](https://news.wheelmap.org/en/improved-wheelmap-test-it-now-and-rate-even-more-places/), [Beta deployment](https://beta.wheelmap.org)). When the beta deployment goes into production, I guess we can close this :)

**Comment by opyh** [comment]
This is fixed - the new OSM DB sync process seems to work reliably. The node is now gone as it has no relevant tags for Wheelmap.
