### ISSUE TITLE
Issues remaining from A11Y Improvements

### ISSUE THREAD

**Issue by dakeyras7** [sozialhelden/wheelmap-frontend#8]
There are couple of things that I couldn't finish because of time reasons and also considered them to be smaller glitches, nive-to-haves or just general hints.

**Hints**

- Everything that was implemented was tested by hand. To ensure proper functionality in the future and move fast without breaking too much we need to add End-To-End-Testing for keyboard navigation.
- Aria labels and alt texts need proper translations
- Dynamic colors with cluster markers lead to poor color contrasts between dynamic color of background and number color.
- The marker shapes changed and the design for the map filter button needs to be adapted.
- The copy text of the map filter dialogue should avoid the word "see". Instead of "Which places you want to see", better use "Which places are shown".

**Bugs/Glitches**

- There is a glitch with the icon placement in the onboarding dialog on mobile
- Due to the nature of the new map markers (they are SVGs) now the shadow that appeared before on hover is now gone.
- After searching with the search field and clicking a search result the POI dialog displays the details of the POI. When clicking the close button of the POI dialog we now return to the search result list, but this time the search text is cleared out. This is not a deal breaker, but seems inconsistent.
- If `Tab`ing and `Shift-Tab`ing into and out of the search input field to quickly, focus gets lost sometimes. This is a glitch due to the fact that we use timeouts that are required as workarounds for certain iOS Safari bugs.
- Sometimes after selecting an item in a search result list via keyboard `Enter` the focus gets lost. I suspect that this is also due to timeouts ore some race condition with api fetching.
- During onboarding when hitting `Enter` to fast on the "Ok, let's go" button, the search input field might not be rendered yet and the initial focus can't be set there.

**Nice-To-Have**

* The order of focusable elements on the map is pretty "jumpy". If we like a more top-down, left-to-right we would have to order them in the DOM or give them a ordered tabindex.
* The `Esc` key could be used more consistently to always close what's currently open. At the moment it closes certain modal dialogs.
* The search results list can only be navigated via the `Tab` key. It would be nice if arrow keys also could work here
* Moving the map and changing the zoom only work when the map is currently focused. It would be nice if the arrow keys could move the map all the times except when in a search result list or RadioGroup and when the + and - keys could always manipulate the map zoom. In the latter case we should also tell the users about this feature by displaying some + and - key icons next to the zoom buttons.
* The localize me button should also have a keyboard shortcut

**Comment by opyh** [comment]
Moved this into our internal bugtracker. Thanks!
